config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'home#index'
  resources :users,:only => [:new, :create, :destroy,:show]

  resources :tags,:only => [:show]
  resources :posts, :only => [:new,:create,:destroy,:index,:show] do
    resources :comments, :only => [:new,:create,:destroy] do
      member do 
        get "clike", to: "comments#clike"
        get "cdislike", to: "comments#cdislike" 
      end
      get '/:parent_id', to: 'comments#new', as: :new_comment
    end
    member do
        get "like", to: "posts#like"
        get "dislike", to: "posts#dislike"
    end
  end

  get '/tag/:id', :to => 'tags#show'
  get '/profile/:id', :to => 'posts#show'
  get '/ask', :to => 'posts#new'
  get '/posts', :to => 'posts#index'
  get '/signup',  :to => 'users#new'
  get '/login',  :to => 'sessions#new'
  match '/login',  :to => 'sessions#create', :via => [:get,:post], :as => :post_login
  get 'logout', :to => 'sessions#destroy'

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :users
  belongs_to :posts
  has_many :votecoms

  acts_as_tree order: 'created_at DESC'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	respond_to :json,:html,:js

	def new
		@comment = Comment.new(parent_id: params[:parent_id])
		@post = Post.find(params[:post_id])
	end

	def create
		@content = params[:comment][:content]
		@userid = session[:userid]
		@postid = Post.find(params[:post_id]).id #string of slug

		c = {user_id:@userid,post_id:@postid,content:@content,flag:true}
		if params[:comment][:parent_id].to_i > 0
    	  parent = Comment.find_by_id(params[:comment][:parent_id])
    	  @comment = parent.children.build(c)
  		else
   		  @comment = Comment.new(c)
	    end
		
		if @comment.save
    	  flash[:success] = 'Your comment was successfully added!'
    	  redirect_to post_path(params[:post_id])
  		else
    	  render 'new'
  		end

	end

	def destroy
	end

	def clike
	  postid =  Post.find(params[:post_id]).id	
	  @comid = params[:id]
	  @userid = session[:userid]
	  f = Votecom.where(com_id:@comid,user_id:@userid).first
	  if f != nil
	  	f.update_attributes(vote_type:1)
	  else
	  	Votecom.create(com_id:@comid,user_id:@userid,vote_type:1)
	  end

	  @cliked = Votecom.where("com_id = ? AND vote_type = ?",@comid,1).count
	  @negcliked = Votecom.where("com_id = ? AND vote_type = ?",@comid,-1).count

	  if request.xml_http_request?
        render json: { pcount: @cliked,ncount:@negcliked, id: params[:id] }
      else
        logger.debug "Ajax request false"
      end
      

	  #redirect_to post_path(postid)
	end

	def cdislike
	  postid =  Post.find(params[:post_id]).id	
	  @comid = params[:id]
	  @userid = session[:userid]
	  f = Votecom.where(com_id:@comid,user_id:@userid).first
	  if f != nil
	  	f.update_attributes(vote_type:-1)
	  else
	  	Votecom.create(com_id:@comid,user_id:@userid,vote_type:-1)
	  end
	  
	  @cliked = Votecom.where("com_id = ? AND vote_type = ?",@comid,1).count
	  @negcliked = Votecom.where("com_id = ? AND vote_type = ?",@comid,-1).count

	  if request.xml_http_request?
        render json: { pcount: @cliked,ncount:@negcliked, id: params[:id] }
      else
        logger.debug "Ajax request false"
      end

	  #redirect_to post_path(postid)
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies",style:"margin-left:50px;") : nil)
    end.join.html_safe
  end

  def islikedcom?(comid)
	userid = session[:userid]
	f = Votecom.where(user_id:userid,com_id:comid).first
	if f != nil
		return f.vote_type == 1
	else
		return 2
	end
  end
  
end

app/views/comments/_comment.html.erb
					
					    <li class="comment">
							<%  
										user = User.find(comment.user_id)
							%>
					        <div class="comment-body comment-body-answered clearfix"> 

					                	<div class="comment-vote">
						                	<ul class="question-vote">
<%pc = Votecom.where("com_id = ? AND vote_type = ?",comment.id,1).count
  pcS = "+" + pc.to_s
%>
<span class="question-vote-result" data-id="<%=comment.id%>"><%=pcS%></span>						                		
<% if session[:signed] == true %>
 <% 	ret = islikedcom? comment.id 
 		if ret != true
 %>

       <%= link_to '<i class="fa fa-thumbs-o-up"></i>'.html_safe, clike_post_comment_path(@post.id,:id => comment.id),remote: true, class: 'cvote',style: 'float:right',data: { toggle_href: cdislike_post_comment_path(@post.id,:id => comment.id), id:
comment.id }%>


<%		end 
		if ret != false
%>

      <%= link_to '<i class="fa fa-thumbs-o-down"></i>'.html_safe, cdislike_post_comment_path(@post.id,:id => comment.id),:remote => true, class: 'cvote',style: 'float:right',data: { toggle_href: clike_post_comment_path(@post.id,:id => comment.id), id:
comment.id }%>

<% 		end 
  end
  #negative comment string
  nc = Votecom.where("com_id = ? AND vote_type = ?",comment.id,-1).count
  ncS = "-" + nc.to_s
%>
<span class="question-vote-result2" data-id="<%=comment.id%>"><%=ncS%></span>

						                	</ul>
					                	</div>
					                	
					            <div class="avatar">
					            	<a href="/profile/<%=comment.user_id%>" original-title="ahmed" class="question-author-img tooltip-n"><img alt="" src="/images/profile/avatar.png"></a>

					            	</div>
					            <div class="comment-text">
					                <div class="author clearfix">
					                	<div class="comment-author">
					                <%= link_to user.name, {:controller => "users",:action => "show",:id => comment.user_id} %>
					
					                	</div>
			
					                	<div class="comment-meta">
					                        <div class="date"><i class="fa fa-clock-o"></i><%=time_ago_in_words(comment.created_at)%> ago</div> 
					                    </div>


<% from_reply_form ||= nil %>
<% unless from_reply_form %>

<%= link_to '<i class="fa-mail-reply fa"></i>'.html_safe,post_comment_new_comment_path(@post.friendly_id,comment.id,comment.id),class: 'comment-reply'  %>

<%end%>

					                </div>
					                <div class="text"><blockquote><p><%=comment.content.html_safe%></blockquote></p>
					                </div>
									<div class="question-answered question-answered-done"><i class="fa fa-check"></i>Best Answer</div>
					            </div>
					        </div>
					     </li>

app/views/comments/new.html.erb
 <%= stylesheet_link_tag "/stylesheets/style2.css" %>
 <%= stylesheet_link_tag "/stylesheets/base.css" %>


<div id="commentlist" class="question question-type-normal">
<ol class="commentlist clearfix">
<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>
</ol>
</div>

<%= render 'posts/form' %>