config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'home#index'
  resources :users,:only => [:new, :create, :destroy,:show]

  resources :tags,:only => [:show]
  resources :posts, :only => [:new,:create,:destroy,:index,:show] do
    resources :comments, :only => [:new,:create,:destroy] do
      member do 
        get "clike", to: "comments#clike"
        get "cdislike", to: "comments#cdislike" 
      end
      get '/:parent_id', to: 'comments#new', as: :new_comment
    end
    member do
        get "like", to: "posts#like"
        get "dislike", to: "posts#dislike"
    end
  end

  get '/tag/:id', :to => 'tags#show'
  get '/profile/:id', :to => 'posts#show'
  get '/ask', :to => 'posts#new'
  get '/posts', :to => 'posts#index'
  get '/signup',  :to => 'users#new'
  get '/login',  :to => 'sessions#new'
  match '/login',  :to => 'sessions#create', :via => [:get,:post], :as => :post_login
  get 'logout', :to => 'sessions#destroy'

  root 'home#index'

end

app/models/post.rb
include ActionView::Helpers::SanitizeHelper

class Post < ActiveRecord::Base
  belongs_to :users
  belongs_to :categories 
  has_many :voteposts
  has_many :comments
  has_many :postags
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]	

  validates :content, :presence => true
  validates :title, :presence => true, :uniqueness => true
  after_save :update_words!

  def update_words!
    require 'htmlentities'; require 'nokogiri'
    doc = Nokogiri::HTML.parse(content)
    doc.xpath("//pre").remove.xpath("//code").remove
    words = doc.text.gsub(/\r\n/, '').downcase
    words = HTMLEntities.new.decode(sanitize(words, :tags => []))
    words = words.split(/\ |\.|\,|\!|\?|\//).reject(&:blank?).sort.join(',')
    words.gsub(/[^a-z\,]/i, '').split(',').reject(&:blank?).sort.join(',')
    update_columns(:words => words)
  end
  
  def update_related!
    posts = Post.all; related = {}
    ifd = inverse_document_frequency(posts)
    (posts - [self]).each do |post|
      score = 0
      intersection = self.words.split(',').multiset(post.words.split(','))
      intersection.each { |word| score += ifd[word] }
      related[post.id] = score
    end
    related = related.sort_by { |k,v| v }.reverse
    related = related.collect { |k,v| k }.first(3).join(',')
    update_columns(:related_posts => related)
  end
  
  def related
    Post.where(:id => related_posts.split(','))
  end
  
  def process_words(content)
    require 'htmlentities'; require 'nokogiri'
    doc = Nokogiri::HTML.parse(content)
    doc.xpath("//pre").remove.xpath("//code").remove
    words = doc.text.gsub(/\r\n/, '').downcase
    words = HTMLEntities.new.decode(sanitize(words, :tags => []))
    words = words.split(/\ |\.|\,|\!|\?|\//).reject(&:blank?).sort.join(',')
    words.gsub(/[^a-z\,]/i, '').split(',').reject(&:blank?).sort.join(',')
    self.update_columns(:words => words)
  end

  private

    def inverse_document_frequency(posts)
      words = {}
      posts.each do |post|
      	post.process_words(post.content) if post.words.blank?
        post.words.split(',').uniq.each do |word|
          words[word] = 0 if words[word].nil?
          words[word] += 1
        end
      end
      words.each do |word, freq|
        words[word] = Math.log(posts.size / freq)
      end
      words
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :json,:html,:js

	def new
	  @post = Post.new
	  @tag = Tag.order('rank DESC')
	  @ptag = Postag.where(post_id:@post.id)
	end

	def create 
		@userid = session[:userid]
		if session.has_key?(:userid) == false
			redirect_to '/login'
			return
		end	
		@title = params[:posted][:title]
		@tags = params[:posted][:tags]
		@cat_id = params[:posted][:category]
		@content = params[:posted][:content]
		
		t = @tags.split(/\W+/)

		@post = Post.create(title:@title,content:@content,user_id:@userid,flag:false,cat_id:@cat_id)
		if(@post.id != nil)
			t.each do |tag|
				var = Tag.find_by_name(tag)
				if(var == nil)
					var = Tag.create(name:tag,rank:1)
				else
					var.update_attributes(rank:var.rank + 1)
				end 

				Postag.create(post_id:@post.id,tag_id:var.id)
			end
      		@post.update_related!
      		@post.related.each { |p| p.update_related! }
      		flash[:success] = 'Post was created successfully.'
			redirect_to '/home'
		end

	end


	def index
		@posts = Post.order('id DESC').limit(10)
		@tag = Tag.order('rank DESC')
		@recents = Post.order('id DESC').limit(2)
	end
                    
	def show
	  @post = Post.find(params[:id])
	  @relates = @post.related.first(3)

	  @f = View.find_by_post_id(@post.id)
	  if @f != nil
	  	c = @f.total_view_count + 1
	  	@f.update_attributes(total_view_count:c)
	  else
	  	@f = View.create(post_id:@post.id,total_view_count:1)
	  end

	  @user = User.find(@post.user_id)	 
	  @comment = Comment.new
	  @liked = Votepost.where("post_id = ? AND vote_type = ?",@post.id,1).count
	  @negliked = Votepost.where("post_id = ? AND vote_type = ?",@post.id,-1).count
	
	  @tag = Tag.order('rank DESC')
	  @ptag = Postag.where(post_id:@post.id)
	  @comments = Comment.where(post_id:@post.id).hash_tree
	  @recents = Post.order('id DESC').limit(2)
	end

	def destroy 
	end

	def like
	  @post = Post.find(params[:id])
	  @userid = session[:userid]
	  f = Votepost.where("post_id = ? AND user_id = ?",@post.id,@userid).first
	  if f != nil
	  	f.update_attributes(vote_type:1)
	  else
	  	Votepost.create(post_id:@post.id,user_id:@userid,vote_type:1)
	  end

	  @liked = Votepost.where("post_id = ? AND vote_type = ?",@post.id,1).count
	  @negliked = Votepost.where("post_id = ? AND vote_type = ?",@post.id,-1).count

	  if request.xml_http_request?
        render json: { pcount: @liked,ncount:@negliked, id: @post.id }
      else
        logger.debug "Ajax request false"
      end
      
	  #redirect_to @post
	end

	def dislike
	  @post = Post.find(params[:id])
	  @userid = session[:userid]
	  f = Votepost.where("post_id = ? AND user_id = ?",@post.id,@userid).first
	  if f != nil
	  	f.update_attributes(vote_type:-1)
	  else
	  	Votepost.create(post_id:@post.id,user_id:@userid,vote_type:-1)
	  end
      
      @liked = Votepost.where("post_id = ? AND vote_type = ?",@post.id,1).count
	  @negliked = Votepost.where("post_id = ? AND vote_type = ?",@post.id,-1).count
  
      if request.xml_http_request?
        render json: { pcount: @liked,ncount:@negliked, id: @post.id }
	  end

	  #redirect_to @post
	end

	def isliked?(postid)
		p = Post.find(postid)
		userid = session[:userid]
		f = Votepost.where(user_id:userid,post_id:p).first
		if f != nil
			return f.vote_type == 1
		else
			return 2
		end
	end

	def islikedcom?(comid)
		userid = session[:userid]
		f = Votecom.where(user_id:userid,com_id:comid).first
		if f != nil
			return f.vote_type == 1
		else
			return 2
		end
	end

	def isset
	  if(session[:signed] == false)
	  	redirect_to '/signup'
	  end
	end

	helper_method:isset
	helper_method:isliked?
	helper_method:islikedcom?
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_form.html.erb
 <%= javascript_include_tag "/javascripts/nicEdit.js" %>
<script type="text/javascript">
bkLib.onDomLoaded(function() {
	new nicEditor().panelInstance('area1');

});
</script>

<div id="respond" class="comment-respond page-content clearfix">
    <div class="boxedtitle page-title"><h2>Leave a reply</h2></div>
    
    <%= form_for @comment, :url => post_comments_path(@post) do |f| %>
    <%= f.hidden_field :parent_id %>
    
 <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

        <div id="respond-textarea">
            <p>
                <label class="required" for="comment">Comment<span>*</span></label>
          
                <%= f.text_area :content,cols:'58',rows:'8',id:"area1",placeholder:'Description'%>
            </p>
        </div>
        <p class="form-submit">
        	<%= f.submit "Post Your Answer",id:"publish-question",class: "button color small submit" %>
        </p>
    <%end%>
</div>

app/views/posts/_post.html.erb
				<%
						ct = Comment.where(post_id:post.id)
						c = 0
						f = View.find_by_post_id(post.id)
						if f != nil
							c = f.total_view_count
						end
				%>
					<article class="question question-type-normal">
					<h2>
						<%= link_to post.title, {:action => "show",:id => post.friendly_id} %>
					
					</h2>
					<a class="question-report" href="#">Report</a>
					
					<div class="question-author">	
						<a href="/profile/<%=post.user_id%>" original-title="ahmed" class="question-author-img tooltip-n"><img alt="" src="/images/profile/avatar.png"></a>
					</div>
					<div class="question-inner">
						<div class="clearfix"></div>
						<p class="question-desc"><%=truncate post.content.html_safe, length: 550,:omission => "",:escape => false%>
						<%= link_to 'read more', {:action => "show",:id => post.id} %></p>
						<div class="question-details">
							<span class="question-answered question-answered-done"><i class="fa fa-check"></i>solved</span>
							<span class="question-favorite"><i class="fa fa-star"></i>5</span>
						</div>
						<span class="question-category"><a href="#"><i class="icon-folder"></i>wordpress</a></span>
						<span class="question-date"><i class="fa fa-clock-o"></i><%=time_ago_in_words(post.created_at)%> ago</span>
						<span class="question-comment"><a href="#"><i class="fa fa-comment"></i><%=ct.count%> Answer</a></span>
						<span class="question-view"><i class="fa fa-user"></i><%=c%> views</span>
						<div class="clearfix"></div>
					</div>
				</article>

app/views/posts/_tagwidget.html.erb
				<div class="widget widget_tag_cloud">
					<h3 class="widget_title">Tags</h3>
					<%
						@tag.each do |t|							
					%>
						<%=link_to t.name,{:controller => "tags",:action => "show",:id => t.friendly_id}	 %>
					<%end%>
				</div>

app/views/posts/new.html.erb
 <%= stylesheet_link_tag "/stylesheets/style2.css" %>
 <%= stylesheet_link_tag "/stylesheets/base.css" %>
 <%= javascript_include_tag "/javascripts/nicEdit.js" %>
 <script>
bkLib.onDomLoaded(function() {
	//new nicEditor().panelInstance('area1');
new nicEditor({iconsPath : '/images/nicEditorIcons.gif'}).panelInstance('area1');
});
</script>
  
<% isset %>
<div id="wrap" class="grid_1200">

	<div class="breadcrumbs">
		<section class="container">
			<div class="row">
				<div class="col-md-12">
					<h1>Ask Question</h1>
				</div>
				<div class="col-md-12">
					<div class="crumbs">
						<a href="#">Home</a>
						<span class="crumbs-span">/</span>
						<a href="#">Pages</a>
						<span class="crumbs-span">/</span>
						<span class="current">Ask Question</span>
					</div>
				</div>
			</div><!-- End row -->
		</section><!-- End container -->
	</div><!-- End breadcrumbs -->
	
	<section class="container main-content">
		<div class="row">
			<div class="col-md-9">
				
				<div class="page-content ask-question">
					<div class="boxedtitle page-title"><h2>Ask Question</h2></div>
					
					<p>Get brief answers for your legal queries. Its FREE! </p>
					<div class="form-style form-style-3" id="question-submit">
					<%= form_for(:posted, :url => posts_path) do |f| %>
							<div class="form-inputs clearfix">
								<p>
									<label class="required">Question Title<span>*</span></label>
									<%= f.text_field :title, class: 'form-control input-md', id:'question-title',placeholder: 'Title' %>
									<span class="form-description">Please choose an appropriate title for the question to answer it even easier .</span>
								</p>
								<p>
									<label>Tags</label>
									<%= f.text_field :tags, class: 'form-control input-md',id:'question-title',placeholder: 'Tags' %>
									<span class="form-description">Please choose  suitable Keywords Ex : <span class="color">question , poll</span> .</span>
								</p>
								<p>
									<label class="required">Category<span>*</span></label>
									<span class="select">
										<%= f.collection_select :category,Category.all, :id, :name %>
									</span>
									<span class="form-description">Please choose the appropriate section so easily search for your question .</span>
								</p>
								<label class="required">Details<span>*</span></label>
						   
								<p>
									<%= f.text_area :content,id:'question-details',cols:'58',rows:'8',id:'area1',placeholder:'Description',value:params[:ques]%>
								
									<span class="form-description">Type the description thoroughly and in detail .</span>
								</p>
							</div>
							<p class="form-submit">
							    <%= f.submit "Publish Your Question",id:"publish-question",class: "button color small submit" %>
							</p>
						<%end%>
					</div>
				</div><!-- End page-content -->
			</div><!-- End main -->
			<aside class="col-md-3 sidebar">
				<div class="widget widget_stats">
					<h3 class="widget_title">Stats</h3>
					<div class="">
						<ul>
							<li><i class="fa fa-question"></i>Questions ( <span><%=Post.count%></span> )</li>
							<li><i class="fa fa-comment"></i>Answers ( <span><%=Comment.count%></span> )</li>
						</ul>
					</div>
				</div>
				
				<div class="widget widget_social">
					<h3 class="widget_title">Find Us</h3>
					<ul>
						<li class="rss-subscribers">
							<a href="#" target="_blank">
							<strong>
								<i class="fa fa-rss"></i>
								<span>Subscribe</span><br>
								<small>To RSS Feed</small>
							</strong>
							</a>
						</li>
						<li class="facebook-fans">
							<a href="#" target="_blank">
							<strong>
								<i class="social_icon-facebook"></i>
								<span>5,000</span><br>
								<small>People like it</small>
							</strong>
							</a>
						</li>
						<li class="twitter-followers">
							<a href="#" target="_blank">
							<strong>
								<i class="social_icon-twitter"></i>
								<span>3,000</span><br>
								<small>Followers</small>
							</strong>
							</a>
						</li>
						<li class="youtube-subs">
							<a href="#" target="_blank">
							<strong>
								<i class="fa fa-play"></i>
								<span>1,000</span><br>
								<small>Subscribers</small>
							</strong>
							</a>
						</li>
					</ul>
				</div>
				

				
				<div class="widget widget_highest_points">
					<h3 class="widget_title">Highest points</h3>
					<ul>
						<li>
							<div class="author-img">
								<a href="#"><img width="60" height="60" src="" alt=""></a>
							</div> 
							<h6><a href="#">admin</a></h6>
							<span class="comment">12 Points</span>
						</li>
						<li>
							<div class="author-img">
								<a href="#"><img width="60" height="60" src="" alt=""></a>
							</div> 
							<h6><a href="#">vbegy</a></h6>
							<span class="comment">10 Points</span>
						</li>
						<li>
							<div class="author-img">
								<a href="#"><img width="60" height="60" src="" alt=""></a>
							</div> 
							<h6><a href="#">ahmed</a></h6>
							<span class="comment">5 Points</span>
						</li>
					</ul>
				</div>
				
				<div class="widget widget_tag_cloud">
					<h3 class="widget_title">Tags</h3>
					<%
						@tag.each do |t|							
					%>
						<%=link_to t.name,{:controller => "tags",:action => "show",:id => t.id}	 %>
					<%end%>
				</div>
				
				
				<div class="widget">
					<h3 class="widget_title">Recent Questions</h3>
					<ul class="related-posts">
						<li class="related-item">
							<h3><a href="#">This is my first Question</a></h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
							<div class="clear"></div><span>Feb 22, 2014</span>
						</li>
						<li class="related-item">
							<h3><a href="#">This Is My Second Poll Question</a></h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
							<div class="clear"></div><span>Feb 22, 2014</span>
						</li>
					</ul>
				</div>
				
			</aside><!-- End sidebar -->
		</div><!-- End row -->
	</section><!-- End container -->
	
</div><!-- End wrap -->

app/views/posts/show.html.erb
 <%= stylesheet_link_tag "/stylesheets/style2.css" %>
 <%= stylesheet_link_tag "/stylesheets/base.css" %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=1659450274342868";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	

	<div class="breadcrumbs">
		<section class="container">
			<div class="row">
				<div class="col-md-12">
					<h1><%=@post.title%></h1>
				</div>
				<div class="col-md-12">
					<div class="crumbs">
						<a href="/home">Home</a>
						<span class="crumbs-span">/</span>
						<a href="/posts">Questions</a>
						<span class="crumbs-span">/</span>
						<span class="current"><%=@post.title%></span>
					</div>
				</div>
			</div><!-- End row -->
		</section><!-- End container -->
	</div><!-- End breadcrumbs -->
	
	<section class="container main-content">
		<div class="row">
			<div class="col-md-9">
				<article class="question single-question question-type-normal">
					<h2>
						<%= link_to @post.title, {:controller => "posts",:action => "show",:id => @post.id} %>
					
					</h2>
					<a class="question-report" href="#">Report</a>
					
					<div class="question-inner">
						<div class="clearfix"></div>
						<p class="question-desc"><%=@post.content.html_safe%></p>
		
						<div class="question-details">
							<span class="question-answered question-answered-done"><i class="fa fa-check"></i>solved</span>
							<span class="question-favorite"><i class="fa fa-star"></i>5</span>
						</div>
						<span class="question-category"><a href="#"><i class="fa fa-folder"></i>wordpress</a></span>
						<span class="question-date"><i class="fa fa-clock-o"></i><%=time_ago_in_words(@post.created_at)%> ago</span>
						<span class="question-comment"><a href="#"><i class="fa fa-comment"></i><%=@comments.count%> Answer</a></span>
						<span class="question-view"><i class="fa fa-user"></i><%=@f.total_view_count%> views</span>
					
						<ul class="single-question-vote">
<%  pp = @liked
  ppS = "+" + pp.to_s
%>
<span class="single-question-vote-result" style= 'float:right' data-id="<%= @post.id %>"><%=ppS%></span>
<% if session[:signed] == true %>
 <% 	ret = isliked? @post.id 
 		if ret != true
 %>

       <%= link_to '<i class="fa fa-thumbs-up"></i>'.html_safe, like_post_path(@post),remote: true, class: 'vote',style: 'float:right',data: { toggle_href: dislike_post_path(@post), id:
@post.id }%>


<%		end 
		if ret != false
%>

      <%= link_to '<i class="fa fa-thumbs-down"></i>'.html_safe, dislike_post_path(@post),:remote => true, class: 'vote',style: 'float:right',data: { toggle_href: like_post_path(@post), id:
@post.id }%>

<% 		end 
  end

  #negative post string
  np = @negliked
  npS = "-" + np.to_s
%>
<span class="single-question-vote-result2"  style= 'float:right' data-id="<%= @post.id %>"><%=npS%></span>

						</ul>
						<div class="clearfix"></div>
					</div>
				</article>
				
				<div class="share-tags page-content">
					<div class="question-tags"><i class="fa fa-tags"></i>

						<%
							@ptag.each do |t|
								obj = Tag.find(t.tag_id)
								tname = obj.name
								tf_id = obj.friendly_id
				
				   		%>	
								<%=link_to tname,{:controller => "tags",:action => "show",:id => tf_id}	 %>
						<%end%>


					</div>
					<div class="fb-share-button" data-href="<%=request.original_url%>" data-layout="icon_link"></div>
					<div class="share-inside-warp">
						<ul>
							<li>
								<a href="#" original-title="Facebook">
									<span class="icon_i">
										<span class="icon_square" icon_size="20" span_bg="#3b5997" span_hover="#666">
											<i i_color="#FFF" class="social_icon-facebook"></i>
										</span>
									</span>
								</a>

								<a href="#" target="_blank">Facebook</a>
							</li>
							<li>
								<a href="#" target="_blank">
									<span class="icon_i">
										<span class="icon_square" icon_size="20" span_bg="#00baf0" span_hover="#666">
											<i i_color="#FFF" class="social_icon-twitter"></i>
										</span>
									</span>
								</a>
								<a target="_blank" href="#">Twitter</a>
							</li>
							<li>
								<a href="#" target="_blank">
									<span class="icon_i">
										<span class="icon_square" icon_size="20" span_bg="#ca2c24" span_hover="#666">
											<i i_color="#FFF" class="social_icon-gplus"></i>
										</span>
									</span>
								</a>
								<a href="#" target="_blank">Google plus</a>
							</li>
							<li>
								<a href="#" target="_blank">
									<span class="icon_i">
										<span class="icon_square" icon_size="20" span_bg="#e64281" span_hover="#666">
											<i i_color="#FFF" class="social_icon-dribbble"></i>
										</span>
									</span>
								</a>
								<a href="#" target="_blank">Dribbble</a>
							</li>
							<li>
								<a target="_blank" href="#">
									<span class="icon_i">
										<span class="icon_square" icon_size="20" span_bg="#c7151a" span_hover="#666">
											<i i_color="#FFF" class="icon-pinterest"></i>
										</span>
									</span>
								</a>
								<a href="#" target="_blank">Pinterest</a>
							</li>
						</ul>
						<span class="share-inside-f-arrow"></span>
						<span class="share-inside-l-arrow"></span>
					</div><!-- End share-inside-warp -->
					<div class="share-inside"><i class="fa fa-share-alt"></i>Share</div>
					<div class="clearfix"></div>
				</div><!-- End share-tags -->
				
				<div class="about-author clearfix">
				    <div class="author-image">
				    	<a href="/profile/<%=@user.id%>" original-title="ahmed" class="question-author-img tooltip-n"><img alt="" src="/images/profile/avatar.png"></a>

				    </div>
				    <div class="author-bio">
				        <h4>About the Author</h4>
				        <%=@user.name%><br/>
				        <%=@user.about%>
				    </div>
				</div><!-- End about-author -->
				
				<div id="related-posts">
					<h2>Related questions</h2>
					<ul class="related-posts">
						<% @relates.each do |relate|
						%>	
						
						<li class="related-item"><h3><i class="fa fa-angle-double-right"></i>	
						<%= link_to relate.title , {:action => "show",:id => relate.friendly_id} %>
						</h3></li>

						<%end%>
					</ul>
				</div><!-- End related-posts -->
				
				<div id="commentlist" class="page-content">
					<div class="boxedtitle page-title"><h2>Answers ( <span class="color"><%=@comments.count%></span> )</h2></div>
<ol class="commentlist clearfix">
	<%= comments_tree_for @comments %>
</ol><!-- End commentlist -->
				</div><!-- End page-content -->

<%if(session[:signed] == true)%>
	<%=	render 'form' %>	
<%end%>				
				<div class="post-next-prev clearfix">
				    <p class="prev-post">
				        <a href="#"><i class="fa-fast-backward fa"></i>&nbsp;Prev question</a>
				    </p>
				    <p class="next-post">
				        <a href="#">Next question&nbsp;<i class="fa-fast-forward fa"></i></a>                                
				    </p>
				</div><!-- End post-next-prev -->	
			</div><!-- End main -->
			<aside class="col-md-3 sidebar">
				<div class="widget widget_stats">
					<h3 class="widget_title">Stats</h3>
					<div class="">
						<ul>
							<li><i class="fa fa-question"></i> Questions ( <span><%=Post.count%></span> )</li>
							<li><i class="fa fa-comment"></i> Answers ( <span><%=Comment.count%></span> )</li>
						</ul>
					</div>
				</div>
				
				<div class="widget widget_social">
					<h3 class="widget_title">Find Us</h3>
					<ul>
						<li class="rss-subscribers">
							<a href="#" target="_blank">
							<strong>
								<i class="fa fa-rss"></i>
								<span>Subscribe</span><br>
								<small>To RSS Feed</small>
							</strong>
							</a>
						</li>
						<li class="facebook-fans">
							<a href="#" target="_blank">
							<strong>
								<i class="social_icon-facebook"></i>
								<span>5,000</span><br>
								<small>People like it</small>
							</strong>
							</a>
						</li>
						<li class="twitter-followers">
							<a href="#" target="_blank">
							<strong>
								<i class="social_icon-twitter"></i>
								<span>3,000</span><br>
								<small>Followers</small>
							</strong>
							</a>
						</li>
						<li class="youtube-subs">
							<a href="#" target="_blank">
							<strong>
								<i class="fa fa-play"></i>
								<span>1,000</span><br>
								<small>Subscribers</small>
							</strong>
							</a>
						</li>
					</ul>
				</div>

				<div class="widget widget_highest_points">
					<h3 class="widget_title">Highest points</h3>
					<ul>
						<li>
							<div class="author-img">
								<a href="#"><img width="60" height="60" src="/images/admin.jpg" alt=""></a>
							</div> 
							<h6><a href="#">admin</a></h6>
							<span class="comment">12 Points</span>
						</li>
						<li>
							<div class="author-img">
								<a href="#"><img width="60" height="60" src="/images/avatar.png" alt=""></a>
							</div> 
							<h6><a href="#">vbegy</a></h6>
							<span class="comment">10 Points</span>
						</li>
						<li>
							<div class="author-img">
								<a href="#"><img width="60" height="60" src="/images/avatar.png" alt=""></a>
							</div> 
							<h6><a href="#">ahmed</a></h6>
							<span class="comment">5 Points</span>
						</li>
					</ul>
				</div>
				
				<%= render 'tagwidget' %>
				
				<div class="widget">
					<h3 class="widget_title">Recent Questions</h3>
					<ul class="related-posts">
						<% @recents.each do |recent|
						%>	
						<li class="related-item">
						<h3>
						<%= link_to recent.title , {:action => "show",:id => recent.friendly_id} %>
						</h3></li>

						<p class="question-desc"><%=truncate recent.content.html_safe, length: 150,:omission => "",:escape => false%></p>
						<div class="clear"></div><span><%=recent.created_at.to_time.strftime("%B %e at %l:%M %p")%></span>
						<%end%>
					</ul>
				</div>
				
			</aside><!-- End sidebar -->
		</div><!-- End row -->
	</section><!-- End container -->